#!/bin/sh

volume="$(pactl list sinks | grep '^[[:space:]]Volume:' | \head -n $((SINK+1)) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')"
mute="$(pactl get-sink-mute 0 | sed 's/^Mute:\ //g')"

if [ "$mute" = 'yes' ]
then
	echo ""

elif [ "$mute" = 'no' ]
then
	echo "$volume"

else
	echo ""
fi


